# Locally run the plugin in debug mode
[tasks.run-debug]
env = { RUST_LOG = "debug" }
command = "cargo"
args = [
    "run",
    "--",
    "--plugin-id",
    "com.jacobtread.tilepad.vtftk",
    "--connect-url",
    "ws://localhost:8532/plugins/ws",
]

# Locally run the plugin in debug mode (Watching for changes)
[tasks.watch-debug]
env = { RUST_LOG = "debug" }
command = "cargo"
args = [
    "watch",
    "-x",
    "run -- --plugin-id com.jacobtread.tilepad.vtftk --connect-url ws://localhost:8532/plugins/ws",
]
