[plugin]
id = "com.jacobtread.tilepad.vtftk"
name = "VTFTK"
version = "0.0.1"
authors = ["Jacobtread"]
description = "Tilepad VTFTK plugin"

[category]
label = "VTFTK"
icon = "images/vtftk.png"

[[bin.native]]
os = "windows"
arch = "x64"
path = "bin/plugin-windows-x64.exe"

[[bin.native]]
os = "windows"
arch = "x86"
path = "bin/plugin-windows-x86.exe"

[[bin.native]]
os = "linux"
arch = "x64"
path = "bin/plugin-linux-x64"

[[bin.native]]
os = "linux"
arch = "x86"
path = "bin/plugin-linux-x86"

[actions.throw_item]
label = "Throw Items"
description = "Throw the selected items"
inspector = "ui/throw.html"

[actions.throw_barrage]
label = "Throw Barrage"
description = "Throw a barrage of selected items"
inspector = "ui/throw.html"
